baseurl = "http://jackytech.github.io/"
title = "Jacky's Tech"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[services]
[services.disqus]
disqusShortname = "JackyCheng"

[markup.highlight]
style = "github-dark"
lineNos = true
lineNumbersInTable = true
anchorLineNos = true

[markup.tableOfContents]
  endLevel = 4
  ordered = false
  startLevel = 2

[params]
  author = "Jacky Cheng"
  info = "Software Engineer"
  description = "Jacky Cheng's personal blog"
  keywords = "blog,developer,personal,golang,backend"
  avatarurl = "images/IMG_8387.jpeg"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false
  maxSeeAlsoItems = 5

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[params.goatCounter]
  code = "9611hcmu"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/jacky-mcc"
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 2
  url = "https://github.com/mchu1966"
[[params.social]]
  name = "Email"
  icon = "fa-brands fa-at fa-2x"
  weight = 3
  url = "mailto:mchu1966718@gmail.com"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Posts"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "Category"
  weight = 3
  url = "categories/"
[[menu.main]]
  name = "Series"
  weight = 4
  url = "series/"
[[menu.main]]
  name = "Tag"
  weight = 5
  url = "tags/"
[[menus.footer]]
  name = 'Terms'
  pageRef = '/terms'
  weight = 10
[[menus.footer]]
  name = 'Privacy'
  pageRef = '/privacy'
  weight = 20
